import {
  solutions,
  services,
  partners,
  logo,
  hero_image,
} from "../assets/images";
import {
  citrix,
  autodesk,
  ms_work,
  ms_infra,
  ms_digit_app,
  menlo,
  watchguard,
  RSA,
  qualys,
  vectra,
  trend,
  quantom,
  veritas,
  fireEye,
  checkPoint,
  darkTrace,
  broadcom,
  nintex,
  vmWare,
  impreva,
  gold,
} from "../assets/partners";

import { cloud, infra, end_to_end, productivity } from "../assets/solutions";
import {
  infrastructure,
  cloudSec,
  productivitySol,
  endToEnd,
} from "../assets/images";

export const navlink = [
  { href: "#home", label: "Home" },
  { href: "#partners", label: "Partners" },
  { href: "#solutions", label: "Solutions" },
  { href: "#about", label: "About" },
];

export const offers = [
  {
    id: "offer-1",
    image: solutions,
    title: "Solutions",
    content:
      "We provide industry leading cloud productivity, cloud infrastructure, cyber security, data security and architecture and engineering solutions",
  },
  {
    id: "offer-2",
    image: services,
    title: "Services",
    content:
      "From advisory, to project management, system design, implementation, and managed services, we maintain one of the largest pools of certified engineers in the country",
  },
  {
    id: "offer-3",
    image: partners,
    title: "Partners",
    content:
      "Founded in 1988, you are sure that we will be here when you need us",
  },
];

export const products = [
  {
    logo: citrix,
    title: "Citrix",
    width: "70%",
  },
  {
    logo: autodesk,
    title: "AUTODESK",
    width: "61%",
  },
  {
    logo: ms_work,
    title: "MS Modern Work",
  },
  {
    logo: ms_infra,
    title: "MS Infrastructure Azure",
  },
  {
    logo: ms_digit_app,
    title: "MS Digital & App Inno azure",
  },
  {
    logo: menlo,
    title: "Menlo",
    width: "40%",
  },
  {
    logo: watchguard,
    title: "WatchGuard",
  },
  {
    logo: RSA,
    title: "RSA",
  },
  {
    logo: qualys,
    title: "Qualys",
  },
  {
    logo: vectra,
    title: "Vectra",
  },
  {
    logo: quantom,
    title: "Trend Micro",
  },
  {
    logo: veritas,
    title: "Trend Micro",
  },
  {
    logo: fireEye,
    title: "Trend Micro",
  },
  {
    logo: checkPoint,
    title: "Trend Micro",
  },
  {
    logo: darkTrace,
    title: "Trend Micro",
  },
  {
    logo: broadcom,
    title: "Trend Micro",
  },
  {
    logo: nintex,
    title: "Trend Micro",
  },
  {
    logo: vmWare,
    title: "Trend Micro",
  },
  {
    logo: impreva,
    title: "Trend Micro",
  },
  {
    logo: gold,
    title: "Trend Micro",
  },
];

export const solutionsOffer = [
  {
    id: 1,
    title: "Infrastructure",
    subtitle: "Core Infrastructure",
    content:
      "Our solutions in this area build on the Microsoft infrastructure stack, which is the most widely used core-infrastructure platform worldwide today. Shellsoft is the top core infrastructure partner in the country for the past few years, combining world-class skills with the experience gained from deploying for a lot of the top corporations in the country.",
    logo: infra,
    picture: infrastructure,
    width: "50%",
  },
  {
    id: 2,
    title: "Cloud",
    subtitle: "Cloud Enablement",
    content:
      "Virtualization is the backbone of cloud implementation, and we are one of the few in the Philippines with combined expertise in the most widely used virtualization platforms today (Microsoft, Citrix, VMware). We also provide storage solutions for the ever growing amount of data generated by cloud and enterprise implementations.",
    logo: cloud,
    picture: cloudSec,
    width: "50%",
    height: "500rem",
  },
  {
    id: 3,
    title: "End-to-End",
    subtitle: "End-to-End Security",
    content:
      "Shellsoft offers cutting-edge security solutions tailored to evolving threat landscapes. Our Adaptive Security portfolio, paired with extensive consulting services, ensures robust protection aligned with industry standards. Leveraging the Microsoft infrastructure stack, we provide scalable and efficient solutions, backed by years of top-tier partnership and deployment experience.",
    logo: end_to_end,
    picture: endToEnd,
  },
  {
    id: 4,
    title: "Productivity",
    subtitle: "Productivity",
    content:
      "Our productivity solutions not only center on desktop productivity and business intelligence, but also help customers needs in the fields of data management, publishing and document management, and workflow.",
    logo: productivity,
    picture: productivitySol,
  },
];

export const about_us = [
  {
    content:
      "Founded in 1988, Shellsoft provides top-tier productivity, security, and data center solutions. Recognized by Microsoft and Symantec Philippines, they excel in virtualization and core infrastructure. With the largest team of certified engineers in-country, Shellsoft serves leading corporations across diverse industries.",
  },
  {
    content:
      "Shellsoft positions itself as a one-stop shop for businesses seeking IT solutions. They offer a wide range of services, from core infrastructure and virtualization to security, data management, and endpoint management. Their large team of certified engineers ensures they can handle complex projects simultaneously while providing clients with the best available skills.",
  },
  {
    content:
      "Founded in 1988, Shellsoft's mission is to provide cutting edge productivity, security and data center solutions at great value. In its more than 25 years of existence, Shellsoft has a reputation among its customers of delivering quality installations using best-of-breed products. As a systems integrator for the world's leading technology companies, Shellsoft is in a unique position to understand the needs of our customers and package the right solutions for them.",
  },
  {
    content:
      "Repeatedly recognized as the top core infrastructure partner by Microsoft Philippines and top security infrastructure partner by Symantec Philippines, Shellsoft is also the leader in virtualization design and implementation, certified by Microsoft, VMware and Citrix for their respective solutions.",
  },
  {
    content:
      "Shellsoft combines expertise and experience in the areas of core infrastructure, virtualization, enterprise and mobile security, data management, workflow, systems and endpoint management and productivity to provide our customers a wide range of advice and solutions to address their business needs",
  },
  {
    content:
      "Shellsoft maintains the single largest group of certified engineers for each of our core products in-country, so that our customers are not only assured of world- standard skills, but also of our ability to do simultaneous, complex projects.",
  },
  {
    content:
      "Shellsoft's customer base is among the most diverse in the industry today, counting the top corporations in the country. We are top supplier of IT solutions to banking and financial institutions and business process outsourcing outfits, as well as the healthcare, retail, manufacturing, utilities, hospitality, real estate, semiconductor, academic and government sectors.",
  },
];
